import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientWrapper from "@/components/ClientComponent";
import { AuthProvider } from "@/context/AuthContect";
import { ContentProvider } from "@/context/ContentContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "reFresh product",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ClientWrapper>
                    <ContentProvider>
                        <AuthProvider>
                            <Header />
                            {children}
                            <Footer />
                        </AuthProvider>
                    </ContentProvider>
                </ClientWrapper>
            </body>
        </html>
    );
}
